theme: jekyll-theme-cayman
title: Distributed Algorithms for Connectivity and MST in Large Graphs with Efficient Local Computation
tagline: ICDCN 2022
author: >-
  Eric Ajieren,
  Khalid Hourani,
  William K. Moses Jr.,
  Gopal Pandurangan
paper_url: ./paper/main.pdf
presentation_url: ./slides/docs/index.html
