theme: jekyll-theme-cayman
title: Distributed Algorithms for Connectivity and MST in Large Graphs with Efficient Local Computation
tagline: ICDCN 2022
description: >-
  Eric Ajieren,
  Khalid Hourani,
  William K. Moses Jr.,
  Gopal Pandurangan
ext-js: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
